#!/usr/bin/env bash

# Copyright 2021 Red Hat, Inc.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# This script will run any command and retry until the command exits
# successfully.
#
# Usage:
#     ./retry 10 5 sudo dnf -y install python3-openstackclient
#
# This will attempt installing openstackclient up to 10 times with a pause of 5
# seconds between retries.

set -Eeuo pipefail

DEBUG=${DEBUG:-}
if [ -n "$DEBUG" ]; then
    set -x
fi

declare \
	retries=$1 \
	time=$2 \
	count=0
shift 2

until "$@"; do
	exit=$?
	count=$((count + 1))
	if [ $count -lt "$retries" ]; then
		>&2 echo "Failed to execute '${@}' after ${count} attempts, will retry in ${time} seconds..."
		sleep "$time"
	else
		>&2 echo "Failed to execute '${@}' after ${count} attempts, exiting."
		exit $exit
	fi
done
