FROM registry.access.redhat.com/ubi8/ubi

COPY ./retry /usr/bin/

RUN retry 5 30 dnf -y install python3 && dnf clean all
RUN retry 5 30 python3 -m pip install pycodestyle

RUN groupadd -r bugwatcher && useradd --create-home --no-log-init -r -g bugwatcher bugwatcher
USER bugwatcher:bugwatcher

WORKDIR /src
COPY ./pretriage/ ./

RUN retry 5 30 python3 -m pip install --user --requirement requirements.txt

ENTRYPOINT [ "./main.py" ]
