FROM fedora:34

WORKDIR /src
COPY ./pretriage/ ./

RUN sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/fedora-cisco-openh264.repo \
	&& sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/fedora-modular.repo \
	&& sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/fedora-updates-modular.repo

RUN ./dnf_safe -y update \
	&& ./dnf_safe -y install pip \
	&& dnf clean all

RUN pip install --upgrade pip && pip install pycodestyle
RUN pip install --requirement requirements.txt
